export { default as Article } from './Article/Article';
export { default as Articles } from './Article/Articles';
export { default as ChangeArticle } from './Article/ChangeArticle';
export { default as RegisterArticle } from './Article/RegisterArticle';
export { default as Categories } from './Category/Categories';
export { default as ChangeCategory } from './Category/ChangeCategory';
export { default as RegisterCategory } from './Category/RegisterCategory';
export { default as Main } from './Main';
export { default as NotFound } from './NotFound';